websites = {
    "YouTube": "https://www.youtube.com",
    "Wikipedia": "https://www.wikipedia.org",
    "Google": "https://www.google.com",
    "Amazon": "https://www.amazon.com",
    "Facebook": "https://www.facebook.com",
    "Twitter": "https://www.twitter.com",
    "Instagram": "https://www.instagram.com",
    "LinkedIn": "https://www.linkedin.com",
    "TikTok": "https://www.tiktok.com",
    "Netflix": "https://www.netflix.com",
    "Times of India": "https://timesofindia.indiatimes.com",
    "BBC News": "https://www.bbc.com/news",
    "CNN": "https://www.cnn.com",
    "The Guardian": "https://www.theguardian.com",
    "Al Jazeera": "https://www.aljazeera.com",
    "Reuters": "https://www.reuters.com",
    "Weather.com": "https://weather.com",
    "AccuWeather": "https://www.accuweather.com",
    "Flipkart": "https://www.flipkart.com",
    "eBay": "https://www.ebay.com",
    "AliExpress": "https://www.aliexpress.com",
    "Khan Academy": "https://www.khanacademy.org",
    "Coursera": "https://www.coursera.org",
    "Udemy": "https://www.udemy.com",
    "edX": "https://www.edx.org",
    "Bloomberg": "https://www.bloomberg.com",
    "CNBC": "https://www.cnbc.com",
    "Yahoo Finance": "https://finance.yahoo.com",
    "MarketWatch": "https://www.marketwatch.com",
    "Screener": "https://www.screener.in",
    "Google Drive": "https://drive.google.com",
    "Microsoft Office Online": "https://www.office.com",
    "Trello": "https://trello.com",
    "Notion": "https://www.notion.so",
    "Slack": "https://slack.com",
    "Canva": "https://www.canva.com",
    "Adobe Creative Cloud": "https://www.adobe.com/creativecloud.html",
    "Unsplash": "https://unsplash.com",
    "Dribbble": "https://www.dribbble.com",
    "Behance": "https://www.behance.net",
    "GitHub": "https://github.com",
    "Stack Overflow": "https://stackoverflow.com",
    "CodePen": "https://codepen.io",
    "MDN Web Docs": "https://developer.mozilla.org",
    "Booking.com": "https://www.booking.com",
    "Expedia": "https://www.expedia.com",
    "TripAdvisor": "https://www.tripadvisor.com",
    "Airbnb": "https://www.airbnb.com",
    "WebMD": "https://www.webmd.com",
    "Mayo Clinic": "https://www.mayoclinic.org",
    "Healthline": "https://www.healthline.com",
    "MyFitnessPal": "https://www.myfitnesspal.com",
    "IMDb": "https://www.imdb.com",
    "Twitch": "https://www.twitch.tv",
    "Steam": "https://store.steampowered.com",
    "Reddit": "https://www.reddit.com",
    "Gmail": "https://mail.google.com",
    "Outlook": "https://outlook.live.com",
    "Zoom": "https://zoom.us",
    "Discord": "https://discord.com",
    "Pinterest": "https://www.pinterest.com",
    "Quora": "https://www.quora.com",
    "Medium": "https://medium.com",
    "Spotify": "https://www.spotify.com",
    "SoundCloud": "https://soundcloud.com",
    "Pandora": "https://www.pandora.com",
    "GitLab": "https://gitlab.com",
    "Bitbucket": "https://bitbucket.org",
    "DigitalOcean": "https://www.digitalocean.com",
    "Heroku": "https://www.heroku.com",
    "Docker Hub": "https://hub.docker.com",
    "Python.org": "https://www.python.org",
    "Node.js": "https://nodejs.org",
    "NPM": "https://www.npmjs.com",
    "PyPI": "https://pypi.org",
    "TensorFlow": "https://www.tensorflow.org",
    "Kaggle": "https://www.kaggle.com",
    "GitKraken": "https://www.gitkraken.com",
    "Git Bash": "https://git-scm.com",
    "MongoDB": "https://www.mongodb.com",
    "PostgreSQL": "https://www.postgresql.org",
    "MySQL": "https://www.mysql.com",
    "Redis": "https://redis.io",
    "SQLite": "https://www.sqlite.org",
    "Anaconda": "https://www.anaconda.com",
    "Jupyter": "https://jupyter.org",
    "VS Code": "https://code.visualstudio.com",
    "JetBrains": "https://www.jetbrains.com",
    "Eclipse": "https://www.eclipse.org",
    "Atom": "https://atom.io",
    "Sublime Text": "https://www.sublimetext.com",
    "New York Times": "https://www.nytimes.com",
    "The Washington Post": "https://www.washingtonpost.com",
    "HuffPost": "https://www.huffpost.com",
    "The Hindu": "https://www.thehindu.com",
    "NDTV News": "https://www.ndtv.com",
    "IGN": "https://www.ign.com",
    "Kotaku": "https://kotaku.com",
    "Polygon": "https://www.polygon.com",
    "Miniclip": "https://www.miniclip.com",
    "Kongregate": "https://www.kongregate.com",
    "Pogo": "https://www.pogo.com",
    "Armor Games": "https://armorgames.com",
    "Crazy Games": "https://www.crazygames.com",
    "Addicting Games": "https://www.addictinggames.com",
    "Agar.io": "https://agar.io",
    "Skribbl.io": "https://skribbl.io",
    "Coolmath Games": "https://www.coolmathgames.com",
    "Bored Panda": "https://www.boredpanda.com",
    "Free Rice": "https://freerice.com",
    "Primary Games": "https://www.primarygames.com",
    "Newgrounds": "https://www.newgrounds.com",
    "Armor Games": "https://www.armorgames.com",
    "Big Fish Games": "https://www.bigfishgames.com",
    "NPR": "https://www.npr.org",
    "Axios": "https://www.axios.com",
    "Vox": "https://www.vox.com",
    "CNET": "https://www.cnet.com",
    "TechCrunch": "https://www.techcrunch.com",
    "The Verge": "https://www.theverge.com",
    "gpt": "https://www.chatgpt.com/"
}
